/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_exchange_jni_MatchingEngineJNI */

#ifndef _Included_com_example_exchange_jni_MatchingEngineJNI
#define _Included_com_example_exchange_jni_MatchingEngineJNI
#ifdef __cplusplus
extern "C"
{
#endif

  JNIEXPORT jlong JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_createMatchingEngine(JNIEnv *, jobject, jstring);

  JNIEXPORT jstring JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_printHello(JNIEnv *, jobject);

  JNIEXPORT jstring JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_insertOrder(JNIEnv *, jobject, jlong, jstring, jstring, jint, jint);
  JNIEXPORT void JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_deleteMatchingEngine(JNIEnv *env, jobject obj, jlong ptr);
  JNIEXPORT jstring JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_getMatchingEngineSummary(JNIEnv *env, jobject obj, jlong ptr);
  
#ifdef __cplusplus
}
#endif
#endif